import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.loginbox}>
          <form>
            <h2>Login</h2>
            <div className={styles.inputbox}>
              <input type="email" placeholder='Email' required/>
              

            </div>

            <div className={styles.inputbox}>
              
              <input type="password" placeholder='Senha' required/>
              
            </div>
            
            <div className={styles.remember}>
                <label><input type="checkbox"/>Lembrar senha</label>
                <a href="#">Esqueci minha senha</a>
            </div>
            <button type='submit'>Login</button>
            <div className={styles.register}>
<<<<<<< HEAD
              <p>Não tem uma conta?<a href="register">Registra-se</a></p>
=======
              <p>Não tem uma conta? <a href="#">Cadastrar</a></p>
>>>>>>> 0d6563fb914fe5533f23bf9d966b382df83a79b0
            </div>
          </form>

        
        </div>
        
       
      </main>

      
    </>
  )
}
