import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.loginbox}>
          <form>
            <h2>Criar Conta</h2>
            <div className={styles.inputbox}>
              <input type="text" placeholder='Nome Completo' required/>
            </div>

            <div className={styles.inputbox}>
              <input type="email" placeholder='Email' required/>
            </div>

            <div className={styles.inputbox}>
              
              <input type="password" placeholder='Senha' required/>
              
            </div>
            
            <button type='submit'>Criar</button>
            
          </form>

        
        </div>
        
       
      </main>
    </>
  )  
}